window.SF=window.SF||{};
(()=>{'use strict';
const S=window.SF,$=id=>document.getElementById(id);let state=S.newProject(),installPrompt=null,saveTimer=null,generatedPdfBytes=null,generatedPdfName='';
const defs=[
 ['nomeSposa','Nome sposa','text'],
 ['nomeSposo','Nome sposo','text'],
 ['dataEvento','Data evento','date'],
 ['cerimonia','Luogo e indirizzo cerimonia','text'],
 ['ricevimento','Luogo e indirizzo ricevimento','text'],
 ['responsabile','Responsabile in loco','text'],
 ['telefono','Telefono responsabile','tel']
];
document.addEventListener('DOMContentLoaded',init);
async function init(){wire();renderFields();const last=localStorage.getItem('sf-last');if(last)state=S.migrateProject((await S.get(S.PROJECTS,last))||state);renderAll();await renderTemplate();if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js?v=37').catch(console.warn)}
function wire(){
 $('newBtn').onclick=newProject;$('drawerNewBtn').onclick=newProject;$('archiveBtn').onclick=()=>{$('archiveDrawer').hidden=false;renderArchive()};$('closeArchive').onclick=()=>$('archiveDrawer').hidden=true;$('archiveDrawer').onclick=e=>{if(e.target===$('archiveDrawer'))$('archiveDrawer').hidden=true};
 $('installBtn').onclick=install;$('closeInstall').onclick=()=>$('installModal').hidden=true;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});
 $('addProposalBtn').onclick=()=>{state.pagine.push({id:S.uuid(),sezione:'LA NOSTRA PROPOSTA PER VOI',titolo:'',testoIntro:'',prezzoTesto:'',immagini:[]});changed();renderProposals()};
 $('addRowBtn').onclick=()=>{state.preventivo.voci.push({id:S.uuid(),descrizione:'',quantita:1,prezzoUnitario:0});changed();renderPricing();renderTotals()};
 $('laborPct').oninput=e=>{state.preventivo.manodoperaPct=S.num(e.target.value);changed();renderTotals()};
 $('plannerPct').oninput=e=>{state.preventivo.weddingPlannerPct=S.num(e.target.value);changed();renderTotals()};
 $('vatPct').oninput=e=>{state.preventivo.ivaPct=S.num(e.target.value);changed();renderTotals()};
 $('bonusDesc').oninput=e=>{state.preventivo.bonusDesc=e.target.value;changed()};$('bonusValue').oninput=e=>{state.preventivo.bonusValue=S.num(e.target.value);changed()};
 $('generateBtn').onclick=generate;$('sharePdfBtn').onclick=shareGeneratedPdf;$('downloadPdfBtn').onclick=downloadGeneratedPdf;$('backupBtn').onclick=backup;$('importBtn').onclick=()=>$('importFile').click();$('importFile').onchange=async e=>{const f=e.target.files?.[0];if(f)await importBackup(f);e.target.value=''};
 $('templateInput').onchange=async e=>{const f=e.target.files?.[0];if(f)await saveTemplate(f);e.target.value=''};$('storyRange').onchange=updateRanges;$('testRange').onchange=updateRanges;
}
function renderFields(){$('contractFields').innerHTML=defs.map(([k,l,t])=>`<label class="field"><span>${l}</span><input data-d="${k}" type="${t}"></label>`).join('');document.querySelectorAll('[data-d]').forEach(el=>el.oninput=e=>{state.dati[e.target.dataset.d]=e.target.value;changed();renderHeader()})}
function renderAll(){state=S.migrateProject(state);document.querySelectorAll('[data-d]').forEach(el=>el.value=state.dati[el.dataset.d]??'');$('laborPct').value=state.preventivo.manodoperaPct??20;$('plannerPct').value=state.preventivo.weddingPlannerPct??0;$('vatPct').value=state.preventivo.ivaPct??22;$('bonusDesc').value=state.preventivo.bonusDesc||'';$('bonusValue').value=state.preventivo.bonusValue||'';renderHeader();renderProposals();renderPricing();renderTotals()}
function title(){return[state.dati.nomeSposa,state.dati.nomeSposo].filter(Boolean).join(' e ')||'Nuovo matrimonio'}
function renderHeader(){const t=S.calc(state);$('projectTitle').textContent=title();$('projectSub').textContent=`${state.dati.dataEvento||'Data evento da inserire'} · ${S.euro(t.total)}`}
function normalizeProposal(p){
 p.immagini=Array.isArray(p.immagini)?p.immagini:[];
 for(const im of p.immagini)if(im.descrizione==null)im.descrizione='';
 if(p.testoIntro==null)p.testoIntro='';
 if(!String(p.testoIntro).trim()&&p.testo){p.testoIntro=String(p.testo);p.testo=''}
 const first=p.immagini[0],firstDesc=String(first?.descrizione||'').trim();
 if(!String(p.testoIntro).trim()&&first&&firstDesc.length>220){p.testoIntro=firstDesc;first.descrizione=''}
 return p
}
function imageCard(im,i,total){return `<div class="proposal-image-card" data-im="${im.id}"><div class="proposal-image-preview"><img src="${im.dataUrl}" alt="Immagine proposta"><div class="proposal-image-actions"><button type="button" data-imove="-1" ${i===0?'disabled':''} title="Sposta indietro">←</button><button type="button" data-imove="1" ${i===total-1?'disabled':''} title="Sposta avanti">→</button><button type="button" data-rm="${im.id}" class="danger" title="Rimuovi">×</button></div></div><label class="field proposal-caption"><span>Descrizione immagine</span><textarea data-imdesc placeholder="Descrizione breve che comparirà sotto questa immagine">${S.esc(im.descrizione||'')}</textarea></label></div>`}
function renderProposals(){
 const root=$('proposalList');if(!state.pagine.length){root.innerHTML='<div class="empty">Nessuna pagina. Aggiungi la prima pagina della proposta.</div>';return}
 root.innerHTML=state.pagine.map((raw,i)=>{const p=normalizeProposal(raw);return `<article class="proposal-card" data-id="${p.id}"><div class="proposal-head"><b>Pagina ${i+1}</b><div class="mini-actions"><button data-a="up" ${i===0?'disabled':''}>↑</button><button data-a="down" ${i===state.pagine.length-1?'disabled':''}>↓</button><button data-a="del" class="danger">×</button></div></div><div class="grid two"><label class="field"><span>Intestazione</span><input data-p="sezione" value="${S.attr(p.sezione)}"></label><label class="field"><span>Titolo</span><input data-p="titolo" value="${S.attr(p.titolo)}"></label><label class="field" style="grid-column:1/-1"><span>Testo introduttivo della pagina</span><textarea data-p="testoIntro" rows="5" placeholder="Testo lungo centrato che comparirà prima delle immagini">${S.esc(p.testoIntro||'')}</textarea><small>Usa questo spazio per la spiegazione completa. Le descrizioni sotto le immagini possono restare più concise.</small></label><label class="field" style="grid-column:1/-1"><span>Prezzo / nota pagina</span><textarea data-p="prezzoTesto">${S.esc(p.prezzoTesto||'')}</textarea></label></div><div class="proposal-images-head"><div><b>Immagini e descrizioni</b><small>Massimo 2 immagini per riga nel PDF. Se sono dispari, l’ultima viene centrata.</small></div><label class="btn secondary proposal-upload">+ Aggiungi foto<input data-upload type="file" accept="image/*" multiple hidden></label></div><div class="proposal-image-grid">${p.immagini.map((im,j)=>imageCard(im,j,p.immagini.length)).join('')}</div></article>`}).join('');
 root.querySelectorAll('.proposal-card').forEach(card=>{const id=card.dataset.id,p=normalizeProposal(state.pagine.find(x=>x.id===id));card.querySelectorAll('[data-p]').forEach(el=>el.oninput=e=>{p[e.target.dataset.p]=e.target.value;changed()});card.querySelector('[data-a="up"]')?.addEventListener('click',()=>movePage(id,-1));card.querySelector('[data-a="down"]')?.addEventListener('click',()=>movePage(id,1));card.querySelector('[data-a="del"]')?.addEventListener('click',()=>{if(confirm('Rimuovere questa pagina?')){state.pagine=state.pagine.filter(x=>x.id!==id);changed();renderProposals()}});card.querySelectorAll('[data-im]').forEach(imCard=>{const im=p.immagini.find(x=>x.id===imCard.dataset.im);imCard.querySelector('[data-imdesc]').oninput=e=>{im.descrizione=e.target.value;changed()};imCard.querySelector('[data-rm]').onclick=()=>{p.immagini=p.immagini.filter(x=>x.id!==im.id);changed();renderProposals()};imCard.querySelectorAll('[data-imove]').forEach(btn=>btn.onclick=()=>moveImage(p,im.id,Number(btn.dataset.imove)))});const up=card.querySelector('[data-upload]');if(up)up.onchange=async e=>{const files=[...e.target.files];for(const f of files)p.immagini.push({id:S.uuid(),dataUrl:await S.imageToJpeg(f),descrizione:''});e.target.value='';changed();renderProposals()}})
}
function moveImage(p,id,d){const i=p.immagini.findIndex(x=>x.id===id),j=i+d;if(i<0||j<0||j>=p.immagini.length)return;[p.immagini[i],p.immagini[j]]=[p.immagini[j],p.immagini[i]];changed();renderProposals()}
function movePage(id,d){const i=state.pagine.findIndex(x=>x.id===id),j=i+d;if(i<0||j<0||j>=state.pagine.length)return;[state.pagine[i],state.pagine[j]]=[state.pagine[j],state.pagine[i]];changed();renderProposals()}
function renderPricing(){const body=$('pricingRows');body.innerHTML=state.preventivo.voci.map(v=>`<tr data-id="${v.id}"><td><input data-r="descrizione" value="${S.attr(v.descrizione)}" placeholder="es. Centrotavola"></td><td><input data-r="quantita" type="number" min="0" step="0.1" value="${v.quantita}"></td><td><input data-r="prezzoUnitario" type="number" min="0" step="0.01" value="${v.prezzoUnitario}"></td><td class="row-total">${S.euro(S.num(v.quantita)*S.num(v.prezzoUnitario))}</td><td><button class="danger" data-del>×</button></td></tr>`).join('');body.querySelectorAll('tr').forEach(tr=>{const v=state.preventivo.voci.find(x=>x.id===tr.dataset.id);tr.querySelectorAll('[data-r]').forEach(el=>el.oninput=e=>{const k=e.target.dataset.r;v[k]=k==='descrizione'?e.target.value:S.num(e.target.value);tr.querySelector('.row-total').textContent=S.euro(S.num(v.quantita)*S.num(v.prezzoUnitario));changed();renderTotals()});tr.querySelector('[data-del]').onclick=()=>{state.preventivo.voci=state.preventivo.voci.filter(x=>x.id!==v.id);changed();renderPricing();renderTotals()}})}
function renderTotals(){const t=S.calc(state);$('totals').innerHTML=[['Base',t.base],['Manodopera',t.lab],['Wedding planner',t.planner],['Imponibile',t.taxable],['IVA',t.vat],['Totale',t.total],['Caparra 30%',t.deposit],['Saldo 70%',t.balance]].map(([k,v])=>`<div class="total-cell ${k==='Totale'?'grand':''}"><small>${k}</small><b>${S.euro(v)}</b></div>`).join('');renderHeader()}
function clearGeneratedPdf(){generatedPdfBytes=null;generatedPdfName='';const box=$('pdfReady');if(box)box.hidden=true}
function changed(){clearGeneratedPdf();$('saveState').textContent='Salvataggio…';$('saveState').classList.add('saving');clearTimeout(saveTimer);saveTimer=setTimeout(save,450)}
async function save(){state.updatedAt=new Date().toISOString();await S.put(S.PROJECTS,state);localStorage.setItem('sf-last',state.id);$('saveState').textContent='Salvato';$('saveState').classList.remove('saving')}
async function newProject(){await save();state=S.newProject();renderAll();clearGeneratedPdf();changed();$('archiveDrawer').hidden=true}
async function renderArchive(){const list=(await S.all(S.PROJECTS)).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));$('archiveList').innerHTML=list.length?list.map(p=>{p=S.migrateProject(p);const tt=S.calc(p);return`<div class="archive-item"><b>${S.esc([p.dati.nomeSposa,p.dati.nomeSposo].filter(Boolean).join(' e ')||'Senza nome')}</b><div class="meta">${p.dati.dataEvento||'Data non inserita'} · ${S.euro(tt.total)}</div><div class="btns"><button data-open="${p.id}">Apri</button><button class="danger" data-delete="${p.id}">Elimina</button></div></div>`}).join(''):'<div class="empty">Nessun preventivo salvato.</div>';$('archiveList').querySelectorAll('[data-open]').forEach(b=>b.onclick=async()=>{state=S.migrateProject(await S.get(S.PROJECTS,b.dataset.open));localStorage.setItem('sf-last',state.id);renderAll();clearGeneratedPdf();$('archiveDrawer').hidden=true});$('archiveList').querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(confirm('Eliminare questa bozza?')){await S.del(S.PROJECTS,b.dataset.delete);renderArchive()}})}
async function saveTemplate(file){try{const bytes=await file.arrayBuffer();const pdf=await PDFLib.PDFDocument.load(bytes);if(pdf.getPageCount()<21)throw new Error('Il template deve contenere almeno 21 pagine, incluse le pagine 13-21 del contratto.');await S.put(S.ASSETS,{id:'template',bytes,storyRange:$('storyRange').value,testRange:$('testRange').value,name:file.name,pages:pdf.getPageCount(),savedAt:new Date().toISOString()});clearGeneratedPdf();await renderTemplate()}catch(e){console.error(e);alert(e.message||'PDF non valido o non leggibile.')}}
async function updateRanges(){const t=await S.get(S.ASSETS,'template');if(!t)return;t.storyRange=$('storyRange').value;t.testRange=$('testRange').value;await S.put(S.ASSETS,t);clearGeneratedPdf();renderTemplate()}
async function renderTemplate(){const t=await S.get(S.ASSETS,'template');if(!t){$('templateStatus').textContent='Template non caricato';$('templateMeta').textContent='Carica “Copia di Meizhi e Ior.pdf” con i PLACEHOLDER nel contratto.';return}$('storyRange').value=t.storyRange||'1-7';$('testRange').value=t.testRange||'11-12';$('templateStatus').textContent='Template pronto';$('templateMeta').textContent=`${t.name||'PDF'} · ${t.pages||'?'} pagine · contratto originale 13-21`}
function validate(){const d=state.dati,missing=[];for(const[k,label]of defs){if(!String(d[k]||'').trim())missing.push(label)}if(!state.preventivo.voci.length)missing.push('almeno una voce di preventivo');return missing}
async function generate(){const btn=$('generateBtn');btn.disabled=true;btn.textContent='GENERAZIONE…';clearGeneratedPdf();try{const missing=validate();if(missing.length&&!confirm(`Mancano: ${missing.join(', ')}.\nVuoi generare comunque il PDF?`))return;await save();const{bytes}=await S.generatePdf(state);generatedPdfBytes=bytes;generatedPdfName=`Preventivo_${S.fileName(title())}.pdf`;$('pdfReady').hidden=false;$('pdfReady').scrollIntoView({behavior:'smooth',block:'nearest'})}catch(e){console.error(e);alert(e.message||'Errore durante la generazione PDF')}finally{btn.disabled=false;btn.textContent='GENERA PDF'}}
async function shareGeneratedPdf(){if(!generatedPdfBytes)return;const file=new File([generatedPdfBytes],generatedPdfName,{type:'application/pdf'}),data={files:[file],title:generatedPdfName};if(!navigator.share){downloadGeneratedPdf();return}if(navigator.canShare&&!navigator.canShare(data)){downloadGeneratedPdf();return}try{await navigator.share(data)}catch(e){if(e?.name==='AbortError')return;console.error(e);alert('Condivisione non disponibile in questo momento. Usa “SCARICA PDF”.')}}
function downloadGeneratedPdf(){if(!generatedPdfBytes)return;const blob=new Blob([generatedPdfBytes],{type:'application/pdf'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=generatedPdfName||'Preventivo.pdf';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1500)}
function backup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`Backup_${S.fileName(title())}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function importBackup(file){try{const x=JSON.parse(await file.text());if(!x.dati||!x.preventivo)throw new Error();x.id=S.uuid();x.createdAt=new Date().toISOString();x.updatedAt=x.createdAt;state=S.migrateProject(x);renderAll();clearGeneratedPdf();changed()}catch{alert('Backup non valido.')}}
async function install(){if(installPrompt){await installPrompt.prompt();installPrompt=null}else $('installModal').hidden=false}
})();
