window.SF=window.SF||{};
(()=>{'use strict';
const S=window.SF;const {PDFDocument,StandardFonts,rgb}=window.PDFLib||{};const PAGE=[595.28,841.89],sage=rgb(.49,.57,.41),dark=rgb(.20,.24,.18),muted=rgb(.42,.44,.40),paper=rgb(.995,.989,.97);
S.generatePdf=async(p,b)=>{if(!window.PDFLib)throw new Error('Motore PDF non disponibile. Controlla la connessione al primo avvio.');const t=S.calc(p),out=await PDFDocument.create(),font=await out.embedFont(StandardFonts.TimesRoman),bold=await out.embedFont(StandardFonts.TimesRomanBold),helv=await out.embedFont(StandardFonts.Helvetica);const tpl=await S.get(S.ASSETS,'template');if(!tpl?.bytes)throw new Error('Carica prima il PDF completo di riferimento nella sezione Template statico.');const src=await PDFDocument.load(tpl.bytes),story=parseRange(tpl.storyRange||'1-7',src.getPageCount()),tests=parseRange(tpl.testRange||'11-12',src.getPageCount());for(const i of story)await copyPage(out,src,i);for(const pg of p.pagine||[])await proposal(out,pg,font,bold);await pricing(out,p,t,font,bold);for(const i of tests)await copyPage(out,src,i);for(const model of S.contractPages(p,b,t))await contract(out,model,font,bold,helv);const bytes=await out.save({useObjectStreams:false});return{bytes,t}};
async function copyPage(out,src,index){const [pg]=await out.copyPages(src,[index]);out.addPage(pg)}
function parseRange(s,max){const set=[];String(s).split(',').forEach(part=>{const m=part.trim().match(/^(\d+)(?:-(\d+))?$/);if(!m)return;let a=+m[1],b=m[2]?+m[2]:a;if(a>b)[a,b]=[b,a];for(let n=a;n<=b;n++)if(n>=1&&n<=max&&!set.includes(n-1))set.push(n-1)});return set}
function basePage(out){const p=out.addPage(PAGE);p.drawRectangle({x:0,y:0,width:PAGE[0],height:PAGE[1],color:paper});p.drawRectangle({x:0,y:PAGE[1]-56,width:PAGE[0],height:56,color:rgb(.66,.74,.57)});return p}
function text(page,txt,x,y,size,font,color=dark,max=480,line=size*1.35){const words=String(txt||'').split(/\s+/),lines=[];let cur='';for(const w of words){const n=cur?cur+' '+w:w;if(font.widthOfTextAtSize(n,size)>max&&cur){lines.push(cur);cur=w}else cur=n}if(cur)lines.push(cur);for(const ln of lines){page.drawText(ln,{x,y,size,font,color});y-=line}return y}
function center(page,txt,y,size,font,color=dark){const w=font.widthOfTextAtSize(txt,size);page.drawText(txt,{x:(PAGE[0]-w)/2,y,size,font,color});return y}
async function proposal(out,m,font,bold){const p=basePage(out);center(p,(m.sezione||'LA NOSTRA PROPOSTA PER VOI').toUpperCase(),PAGE[1]-35,13,bold,dark);let y=750;if(m.titolo)y=center(p,m.titolo.toUpperCase(),y,15,bold,dark)-28;const ims=(m.immagini||[]).slice(0,3);if(ims.length){const y0=360,h=330,gap=10,margin=50,total=PAGE[0]-2*margin;for(let i=0;i<ims.length;i++){const bytes=dataBytes(ims[i].dataUrl),jpg=await out.embedJpg(bytes),slot=ims.length===1?total:(total-gap*(ims.length-1))/ims.length,x=margin+i*(slot+gap),scale=Math.min(slot/jpg.width,h/jpg.height),w=jpg.width*scale,hh=jpg.height*scale;p.drawImage(jpg,{x:x+(slot-w)/2,y:y0+(h-hh)/2,width:w,height:hh})}y=330}else{p.drawRectangle({x:50,y:380,width:PAGE[0]-100,height:290,borderColor:rgb(.84,.83,.79),borderWidth:1,color:rgb(.96,.95,.92)});y=345}if(m.testo)y=text(p,m.testo,65,y,11,font,dark,PAGE[0]-130,15)-8;if(m.prezzoTesto)text(p,m.prezzoTesto,65,y,11,bold,sage,PAGE[0]-130,15)}
async function pricing(out,p,t,font,bold){const pg=basePage(out);center(pg,'PREVENTIVO',PAGE[1]-35,13,bold,dark);let y=735;for(const v of p.preventivo.voci||[]){y=text(pg,`${v.descrizione||'Voce'} · ${v.quantita||0} × ${S.euro(v.prezzoUnitario)} = ${S.euro(S.num(v.quantita)*S.num(v.prezzoUnitario))}`,55,y,11,font,dark,PAGE[0]-110,16);if(y<260){y=735}}y-=12;pg.drawLine({start:{x:55,y},end:{x:PAGE[0]-55,y},thickness:1,color:rgb(.82,.82,.78)});y-=26;for(const [a,v] of [['Subtotale',t.base],['Manodopera',t.lab],['Imponibile',t.taxable],['IVA',t.vat]]){pg.drawText(a,{x:55,y,size:11,font});pg.drawText(S.euro(v),{x:400,y,size:11,font:bold});y-=20}pg.drawText('TOTALE',{x:55,y:y-4,size:15,font:bold,color:dark});pg.drawText(S.euro(t.total),{x:385,y:y-4,size:15,font:bold,color:dark});y-=42;pg.drawText(`Caparra ${p.preventivo.caparraPct}%: ${S.euro(t.deposit)} · Saldo: ${S.euro(t.balance)}`,{x:55,y,size:11,font:bold,color:sage});if(p.preventivo.bonusDesc){y-=28;text(pg,`BONUS: ${p.preventivo.bonusDesc}${S.num(p.preventivo.bonusValue)>0?` (valore ${S.euro(p.preventivo.bonusValue)})`:''}`,55,y,11,bold,sage,PAGE[0]-110,16)}}
async function contract(out,items,font,bold,helv){const pg=out.addPage(PAGE);pg.drawRectangle({x:0,y:0,width:PAGE[0],height:PAGE[1],color:rgb(1,1,1)});let y=790;for(const it of items){if(it.t==='title'){y=text(pg,it.text,58,y,14,bold,dark,PAGE[0]-116,19)-12}else if(it.t==='h'){y-=5;y=text(pg,it.text,58,y,11,bold,dark,PAGE[0]-116,15)-4}else if(it.t==='b'){y=text(pg,it.text,58,y,10.3,bold,dark,PAGE[0]-116,14)-3}else if(it.t==='sign'){for(const lab of ['Floral Designer','Sposa','Sposo']){pg.drawText(lab,{x:58,y,size:9.5,font:helv,color:muted});pg.drawLine({start:{x:160,y:y-2},end:{x:480,y:y-2},thickness:.6,color:muted});y-=25}y-=6}else{y=text(pg,it.text,58,y,9.7,font,dark,PAGE[0]-116,13.7)-4}if(y<70)break}}
function dataBytes(url){const b64=String(url).split(',')[1]||'',bin=atob(b64),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);return u}
S.sharePdf=async(bytes,name)=>{const blob=new Blob([bytes],{type:'application/pdf'}),file=new File([blob],name,{type:'application/pdf'});if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]})))return navigator.share({title:name,files:[file]});const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),2000)};
})();
